name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: type-check
          script: pyright
        - name: lint
          script: black --check ipc examples

    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up CPython v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
          poetry run python setup.py install
      
      - name: Run checks
        run: poetry run ${{ matrix.script }}
        