name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py-version: ['3.7', '3.x']

    name: ${{ matrix.py-version }} pytest
    steps:
      - uses: actions/checkout@v2

      - name: Set up CPython v${{ matrix.py-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
          poetry run python setup.py install
      
      - name: Run Pytest
        run: poetry run pytest -v